name: CICD for Reasct App

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  # permission to pipeline to push
  #project got permission to write/push
  # i.e workflow ko content write karne ki permission


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

##Now we have to push ths in new branchusing automationaction
## package is JamesIves/github-pages-deploy-action

      - name: Deployto github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build